apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: default
data:
  config.json: |
    {
      "environment" : "dev"
    }
  
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-producer
  namespace: default
data:
  config.json: |
    {
      "environment" : "dev"
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-consumer
  namespace: default
data:
  config.json: |
    {
      "environment" : "dev"
    }
